# Site settings
title: LAKLAK
email: hello@laklak.fr
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laklak.fr" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

plugins:
  - octopress-autoprefixer
sass:
    style: :compressed
